### ISSUE TITLE
perf-tool: compute lock latency

### ISSUE THREAD

**Issue by gireeshpunathil** [eclipse/openj9-utils#25]
Bascially compute
 - how long the lock is held,
 - what is the reason for the delay:
   - heavy contention or 
    - locked code execution latency

an approach would be to split monitor event into monitor enter and monitor exit events, and find the time in between events with matching monitors. compare it with contention data to make inferences.

(there could be other means to do this)

**Comment by mpirvu** [comment]
Resolved by #53
